### ISSUE TITLE
Out-Of-The-Box this is not working. 

### ISSUE THREAD

**Issue by gabrielkunkel** [Foxandxss/angular-webpack-workflow#2]
I get the roughly the following complaint every time I try to run any of the npm commands. The only thing I did was update everything in the package.json.

**Output when I run npm run test:live**
/usr/local/bin/node /usr/local/bin/npm run-script test:live

> angular-webpack-workflow@1.0.0 test:live /Users/gabrielkunkel/WebstormProjects/angular-webpack-workflow
> karma start --auto-watch --no-single-run

Hash: 8344a6c0a9b3c44a5636
Version: webpack 1.12.9
Time: 598ms

ERROR in ./src/tests.webpack.js
Module build failed: ReferenceError: [BABEL] /Users/gabrielkunkel/WebstormProjects/angular-webpack-workflow/src/tests.webpack.js: Unknown option: /Users/gabrielkunkel/WebstormProjects/angular-webpack-workflow/package.json.stage
    at Logger.error (/Users/gabrielkunkel/WebstormProjects/angular-webpack-workflow/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/Users/gabrielkunkel/WebstormProjects/angular-webpack-workflow/node_modules/babel-core/lib/transformation/file/options/option-manager.js:262:18)
    at OptionManager.addConfig (/Users/gabrielkunkel/WebstormProjects/angular-webpack-workflow/node_modules/babel-core/lib/transformation/file/options/option-manager.js:221:10)
    at OptionManager.findConfigs (/Users/gabrielkunkel/WebstormProjects/angular-webpack-workflow/node_modules/babel-core/lib/transformation/file/options/option-manager.js:370:30)
    at OptionManager.init (/Users/gabrielkunkel/WebstormProjects/angular-webpack-workflow/node_modules/babel-core/lib/transformation/file/options/option-manager.js:412:12)
    at File.initOptions (/Users/gabrielkunkel/WebstormProjects/angular-webpack-workflow/node_modules/babel-core/lib/transformation/file/index.js:190:75)
    at new File (/Users/gabrielkunkel/WebstormProjects/angular-webpack-workflow/node_modules/babel-core/lib/transformation/file/index.js:121:22)
    at Pipeline.transform (/Users/gabrielkunkel/WebstormProjects/angular-webpack-workflow/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at Instrumenter.instrumentSync (/Users/gabrielkunkel/WebstormProjects/angular-webpack-workflow/node_modules/isparta-instrumenter-loader/node_modules/isparta/lib/instrumenter.js:64:55)
    at Object.module.exports (/Users/gabrielkunkel/WebstormProjects/angular-webpack-workflow/node_modules/isparta-instrumenter-loader/index.js:20:25)

**Comment by Foxandxss** [comment]
If you update the package.json, it is likely to break, there are some breaking changes with babel. I will check it and update it and fix the errors.

**Comment by Foxandxss** [comment]
I updated this with babel 6 support. I need to update more stuff but I need to check them properly first.

I don't think this is going to give you any more issue.

**Comment by gabrielkunkel** [comment]
Gotcha. Thanks. Dev and Build works now. :+1:
